import type { Metadata } from "next";
import "./globals.css";
import localfont from "next/font/local";

const argent = localfont({
  src: [
    {
      path: "../../public/font/argent-thin.otf",
    },
  ],
  variable: "--font-argent",
});

export const metadata: Metadata = {
  title: "Vidi Catering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"${argent.variable}"}>
      <body>{children}</body>
    </html>
  );
}
