// src/app/layout.tsx
import { Metadata } from "next";
import "./globals.css";
import localfont from "next/font/local";
import React from "react";
import Nav from "./component/Nav"; // Pastikan path ke komponen Nav benar
import { SpeedInsights } from "@vercel/speed-insights/next";

const argent = localfont({
  src: [
    {
      path: "../../public/font/argent-thin.otf",
    },
  ],
  variable: "--font-argent",
});

export const metadata: Metadata = {
  title: "Vidi Catering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${argent.variable}`}>
      <body>
        {/* <Nav /> Pindahkan Nav ke sini jika ingin global */}
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
